// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1QOEfHi9l93UiJmAhxnNtAFB48ZdxRto',
    appId: '1:5708253046:web:5afaabcf4eabe076591c57',
    messagingSenderId: '5708253046',
    projectId: 'flutterauth-d966e',
    authDomain: 'flutterauth-d966e.firebaseapp.com',
    storageBucket: 'flutterauth-d966e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkUGgyVfwWkf6SCSd_MtIhYqwzEKr-IBE',
    appId: '1:5708253046:android:f771479c3086ea0c591c57',
    messagingSenderId: '5708253046',
    projectId: 'flutterauth-d966e',
    storageBucket: 'flutterauth-d966e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGgE5zW4t23voXfeyTU7-cAs5bCN1WdI0',
    appId: '1:5708253046:ios:ed83393d72f87a47591c57',
    messagingSenderId: '5708253046',
    projectId: 'flutterauth-d966e',
    storageBucket: 'flutterauth-d966e.firebasestorage.app',
    iosBundleId: 'com.example.mytravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGgE5zW4t23voXfeyTU7-cAs5bCN1WdI0',
    appId: '1:5708253046:ios:ed83393d72f87a47591c57',
    messagingSenderId: '5708253046',
    projectId: 'flutterauth-d966e',
    storageBucket: 'flutterauth-d966e.firebasestorage.app',
    iosBundleId: 'com.example.mytravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1QOEfHi9l93UiJmAhxnNtAFB48ZdxRto',
    appId: '1:5708253046:web:097e2f45a797367d591c57',
    messagingSenderId: '5708253046',
    projectId: 'flutterauth-d966e',
    authDomain: 'flutterauth-d966e.firebaseapp.com',
    storageBucket: 'flutterauth-d966e.firebasestorage.app',
  );
}
